"""Repository scanning.

The scanner walks a repository once, applying ignore rules, skipping secret and
binary files, and retaining the text contents that analysis needs — subject to
explicit byte budgets. It never executes anything and never follows symlinks
unless the user explicitly enables it.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path

from skillforge.analyzer.ignore import (
    CONTROL_FILE_NAMES,
    IgnoreMatcher,
    IgnorePattern,
    is_ignored_directory_name,
    is_secret_file,
    load_default_patterns,
    parse_gitignore,
)
from skillforge.analyzer.languages import FileCategory, category_for, language_for
from skillforge.logging import get_logger, trace_span
from skillforge.utils.fs import is_probably_binary, read_text_capped
from skillforge.utils.git import GitInfo, read_git_info

logger = get_logger("analyzer.scanner")

DEFAULT_MAX_TOTAL_CONTENT_BYTES = 128 * 1024 * 1024  # 128 MiB

#: Categories never retained: their presence is evidence enough.
_NO_CONTENT_CATEGORIES: frozenset[FileCategory] = frozenset(
    {FileCategory.LOCKFILE, FileCategory.LICENSE, FileCategory.DATA, FileCategory.SECRET}
)

_GENERATED_NAME_MARKERS: tuple[str, ...] = (
    ".min.js",
    ".min.css",
    ".bundle.js",
    ".g.cs",
    ".g.i.cs",
    ".designer.cs",
    ".generated.",
    ".gen.",
    "_pb2.py",
    "_pb2_grpc.py",
    ".pb.go",
    ".pb.cc",
    "assemblyinfo.cs",
    ".freezed.dart",
    ".g.dart",
    ".mapper.dart",
)

_GENERATED_CONTENT_MARKERS: tuple[str, ...] = (
    "do not edit",
    "code generated by",
    "@generated",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "generated by the protocol buffer compiler",
    "this file is generated",
)


class SkipReason(StrEnum):
    """Why a path was not analysed."""

    IGNORED_DIRECTORY = "ignored_directory"
    IGNORED = "ignored"
    NOT_INCLUDED = "not_included"
    SECRET = "secret_file"
    BINARY = "binary"
    TOO_LARGE = "too_large"
    SYMLINK = "symlink"
    NO_CONTENT_POLICY = "content_not_retained"
    CONTENT_BUDGET = "content_budget_exhausted"
    UNREADABLE = "unreadable"
    EMPTY = "empty"
    CONTROL_FILE = "control_file"


@dataclass(frozen=True, slots=True)
class FileRecord:
    """Metadata for one scanned file."""

    path: str
    name: str
    stem: str
    suffix: str
    size: int
    depth: int
    language: str
    category: FileCategory
    is_generated: bool = False

    @property
    def parent(self) -> str:
        return self.path.rsplit("/", 1)[0] if "/" in self.path else "."

    @property
    def is_documentation(self) -> bool:
        return self.category is FileCategory.DOCS

    @property
    def is_manifest(self) -> bool:
        return self.category is FileCategory.MANIFEST

    @property
    def is_source(self) -> bool:
        return self.category in (FileCategory.SOURCE, FileCategory.TEST)


@dataclass(frozen=True, slots=True)
class SkippedFile:
    path: str
    reason: SkipReason
    detail: str = ""


@dataclass
class ScanOptions:
    """Scan limits and filters (mapped from :class:`AnalysisSettings`)."""

    max_file_size: int = 200_000
    max_total_content_bytes: int = DEFAULT_MAX_TOTAL_CONTENT_BYTES
    follow_symlinks: bool = False
    use_ignore_files: bool = True
    include: tuple[str, ...] = ()
    extra_ignore: tuple[str, ...] = ()
    read_contents: bool = True


@dataclass
class ScanResult:
    """Everything the scanner observed about one repository."""

    root: Path
    options: ScanOptions
    files: list[FileRecord] = field(default_factory=list)
    skipped: list[SkippedFile] = field(default_factory=list)
    contents: dict[str, str] = field(default_factory=dict)
    directories: set[str] = field(default_factory=set)
    truncated_files: set[str] = field(default_factory=set)
    git: GitInfo = field(default_factory=GitInfo)
    total_bytes: int = 0
    analyzed_bytes: int = 0
    ignored_entries: int = 0
    warnings: list[str] = field(default_factory=list)

    # ----------------------------------------------------------------- lookup
    def record(self, path: str) -> FileRecord | None:
        for record in self.files:
            if record.path == path:
                return record
        return None

    def read(self, path: str) -> str | None:
        return self.contents.get(path)

    def records_in(self, category: FileCategory) -> list[FileRecord]:
        return [record for record in self.files if record.category is category]

    def records_with_suffix(self, *suffixes: str) -> list[FileRecord]:
        lowered = tuple(suffix.lower() for suffix in suffixes)
        return [
            record
            for record in self.files
            if any(record.name.lower().endswith(suffix) for suffix in lowered)
        ]

    def records_named(self, *names: str) -> list[FileRecord]:
        wanted = {name.lower() for name in names}
        return [record for record in self.files if record.name.lower() in wanted]

    def manifests(self) -> list[FileRecord]:
        return self.records_in(FileCategory.MANIFEST)

    def source_files(self) -> list[FileRecord]:
        return [
            record
            for record in self.files
            if record.category
            in (FileCategory.SOURCE, FileCategory.TEST, FileCategory.BUILD_SCRIPT)
        ]

    def files_under(self, prefix: str) -> list[FileRecord]:
        cleaned = prefix.strip("/")
        if not cleaned or cleaned == ".":
            return list(self.files)
        needle = cleaned + "/"
        return [record for record in self.files if record.path.startswith(needle)]

    def has_directory(self, *relative: str) -> bool:
        candidates = {item.strip("/") for item in relative}
        return bool(candidates & self.directories)

    def directories_matching(self, needle: str) -> list[str]:
        return sorted(path for path in self.directories if needle in path.split("/"))

    def top_level_directories(self) -> list[str]:
        found = {path.split("/", 1)[0] for path in self.directories if "/" not in path}
        return sorted(found)

    def skip_count(self, reason: SkipReason) -> int:
        return sum(1 for item in self.skipped if item.reason is reason)

    @property
    def text_files(self) -> list[FileRecord]:
        return [record for record in self.files if record.path in self.contents]

    def skipped_by_reason(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for item in self.skipped:
            counts[item.reason.value] = counts.get(item.reason.value, 0) + 1
        return dict(sorted(counts.items()))


def _has_generated_name(name: str) -> bool:
    lowered = name.lower()
    return any(marker in lowered for marker in _GENERATED_NAME_MARKERS)


def _looks_generated(content: str) -> bool:
    head = content[:2048].lower()
    return any(marker in head for marker in _GENERATED_CONTENT_MARKERS)


def _compile_extra_patterns(lines: tuple[str, ...], source: str) -> list[IgnorePattern]:
    compiled: list[IgnorePattern] = []
    for line in lines:
        compiled.extend(parse_gitignore(line, source=source))
    return compiled


class _Walker:
    """Single-pass, deterministic directory walker."""

    def __init__(self, result: ScanResult) -> None:
        self.result = result
        self.options = result.options
        self.remaining_budget = result.options.max_total_content_bytes

    def run(self) -> None:
        base = self._base_patterns()
        include = self._include_matcher()
        stack: list[tuple[Path, str, list[IgnorePattern]]] = [(self.result.root, "", base)]
        while stack:
            directory, rel_dir, inherited = stack.pop()
            matchers = list(inherited)
            matchers.extend(self._local_ignore_patterns(directory, rel_dir))
            try:
                entries = sorted(os.scandir(directory), key=lambda entry: entry.name)
            except OSError as exc:
                self.result.warnings.append(f"Cannot read directory {rel_dir or '.'}: {exc}")
                continue
            for entry in entries:
                rel_path = f"{rel_dir}/{entry.name}" if rel_dir else entry.name
                if self._is_symlink(entry) and not self.options.follow_symlinks:
                    self.result.skipped.append(SkippedFile(rel_path, SkipReason.SYMLINK))
                    continue
                try:
                    is_dir = entry.is_dir(follow_symlinks=self.options.follow_symlinks)
                except OSError:
                    self.result.skipped.append(SkippedFile(rel_path, SkipReason.UNREADABLE))
                    continue
                if is_dir:
                    if is_ignored_directory_name(entry.name):
                        self._skip(rel_path, SkipReason.IGNORED_DIRECTORY, entry.name)
                        continue
                    if IgnoreMatcher(matchers).is_ignored(rel_path, is_dir=True):
                        self._skip(rel_path, SkipReason.IGNORED)
                        continue
                    self.result.directories.add(rel_path)
                    stack.append((Path(entry.path), rel_path, matchers))
                    continue
                try:
                    is_file = entry.is_file(follow_symlinks=self.options.follow_symlinks)
                except OSError:
                    is_file = False
                if not is_file:
                    continue
                self._process_file(Path(entry.path), rel_path, entry.name, matchers, include)

    # ------------------------------------------------------------------ helpers
    def _base_patterns(self) -> list[IgnorePattern]:
        patterns: list[IgnorePattern] = []
        if self.options.use_ignore_files:
            patterns.extend(load_default_patterns(self.result.root))
        patterns.extend(_compile_extra_patterns(self.options.extra_ignore, "<config>"))
        return patterns

    def _include_matcher(self) -> IgnoreMatcher | None:
        if not self.options.include:
            return None
        return IgnoreMatcher(_compile_extra_patterns(self.options.include, "<include>"))

    def _local_ignore_patterns(self, directory: Path, rel_dir: str) -> list[IgnorePattern]:
        if not self.options.use_ignore_files:
            return []
        patterns: list[IgnorePattern] = []
        for name in (".skillforgeignore", ".gitignore"):
            candidate = directory / name
            if not candidate.is_file():
                continue
            try:
                text = candidate.read_text(encoding="utf-8", errors="replace")
            except OSError:  # pragma: no cover - unreadable ignore file
                continue
            source = f"{rel_dir}/{name}" if rel_dir else name
            patterns.extend(parse_gitignore(text, source=source, base=rel_dir))
        return patterns

    @staticmethod
    def _is_symlink(entry: os.DirEntry[str]) -> bool:
        try:
            return entry.is_symlink()
        except OSError:  # pragma: no cover - platform specific
            return False

    def _skip(self, path: str, reason: SkipReason, detail: str = "") -> None:
        self.result.skipped.append(SkippedFile(path, reason, detail))
        if reason in (SkipReason.IGNORED, SkipReason.IGNORED_DIRECTORY):
            self.result.ignored_entries += 1

    def _process_file(
        self,
        absolute: Path,
        rel_path: str,
        name: str,
        matchers: list[IgnorePattern],
        include: IgnoreMatcher | None,
    ) -> None:
        if IgnoreMatcher(matchers).is_ignored(rel_path, is_dir=False):
            self._skip(rel_path, SkipReason.IGNORED)
            return
        if include is not None and not include.is_ignored(rel_path, is_dir=False):
            self._skip(rel_path, SkipReason.NOT_INCLUDED)
            return
        if is_secret_file(name):
            self._skip(rel_path, SkipReason.SECRET)
            return
        if name in CONTROL_FILE_NAMES:
            self._skip(rel_path, SkipReason.CONTROL_FILE)
            return
        try:
            size = absolute.stat().st_size
        except OSError:
            self._skip(rel_path, SkipReason.UNREADABLE)
            return
        if size == 0:
            self._skip(rel_path, SkipReason.EMPTY)
            return
        self.result.total_bytes += size

        category = category_for(rel_path)
        if is_probably_binary(absolute):
            self._skip(rel_path, SkipReason.BINARY)
            return

        generated = _has_generated_name(name)
        if self.options.read_contents and category not in _NO_CONTENT_CATEGORIES:
            self._read_content(absolute, rel_path, size, category)
            content = self.result.contents.get(rel_path)
            if content is not None and _looks_generated(content):
                generated = True
        elif category in _NO_CONTENT_CATEGORIES:
            self._skip(rel_path, SkipReason.NO_CONTENT_POLICY, category.value)

        self.result.files.append(
            FileRecord(
                path=rel_path,
                name=name,
                stem=absolute.stem,
                suffix=absolute.suffix.lower(),
                size=size,
                depth=rel_path.count("/"),
                language=language_for(rel_path),
                category=category,
                is_generated=generated,
            )
        )

    def _read_content(
        self, absolute: Path, rel_path: str, size: int, category: FileCategory
    ) -> None:
        if size > self.options.max_file_size:
            self._skip(rel_path, SkipReason.TOO_LARGE, f"{size} bytes")
            return
        if self.remaining_budget <= 0:
            self._skip(rel_path, SkipReason.CONTENT_BUDGET)
            return
        try:
            content, truncated = read_text_capped(absolute, self.options.max_file_size)
        except OSError:
            self._skip(rel_path, SkipReason.UNREADABLE)
            return
        self.remaining_budget -= len(content.encode("utf-8", errors="replace"))
        if truncated:
            self.result.truncated_files.add(rel_path)
        self.result.contents[rel_path] = content
        self.result.analyzed_bytes += len(content.encode("utf-8", errors="replace"))
        logger.debug("read file", extra={"path": rel_path, "category": category.value})


def scan_repository(root: Path, options: ScanOptions | None = None) -> ScanResult:
    """Walk ``root`` and return a :class:`ScanResult`. Deterministic."""
    opts = options or ScanOptions()
    resolved = root.resolve()
    if not resolved.is_dir():
        raise NotADirectoryError(f"Not a directory: {resolved}")
    result = ScanResult(root=resolved, options=opts)
    with trace_span("scan", root=str(resolved)):
        _Walker(result).run()
    result.git = read_git_info(resolved)
    if result.options.read_contents and result.skip_count(SkipReason.CONTENT_BUDGET):
        result.warnings.append(
            "Content budget exhausted; some files were recorded but not read. "
            "Increase analysis.max_total_content_bytes to analyse more."
        )
    logger.debug(
        "scan complete",
        extra={
            "files": len(result.files),
            "skipped": len(result.skipped),
            "bytes": result.total_bytes,
        },
    )
    return result
