"""``skillforge clean`` — remove generated and exported skills safely."""

from __future__ import annotations

import shutil
from pathlib import Path

import typer
from rich.table import Table

from skillforge.cli.common import REPO_ARGUMENT, emit_json, get_state, handle_errors
from skillforge.errors import NotFoundError, SecurityRefusal
from skillforge.exporters import exporter_ids, get_exporter
from skillforge.models import MANIFEST_FILENAME
from skillforge.security.paths import is_within
from skillforge.skills import list_skill_directories


def register(app: typer.Typer) -> None:
    @app.command("clean")
    @handle_errors
    def clean(
        ctx: typer.Context,
        path: Path = REPO_ARGUMENT,
        yes: bool = typer.Option(False, "--yes", help="Actually delete (without it, only lists)."),
        include_exports: bool = typer.Option(
            False, "--include-exports", help="Also remove exported skill directories."
        ),
        json_output: bool = typer.Option(False, "--json", help="Print JSON."),
    ) -> None:
        """Remove generated skills (only directories created by SkillForge)."""
        state = get_state(ctx)
        state.json_mode = state.json_mode or json_output
        repo_root = path.expanduser().resolve()
        if not repo_root.is_dir():
            raise NotFoundError(
                f"Not a directory: {repo_root}",
                hint="pass the path of the repository you want to work on",
            )
        settings = state.settings_for(repo_root)

        targets: list[Path] = []
        skipped: list[tuple[Path, str]] = []
        for directory in list_skill_directories(settings.output_dir(repo_root)):
            if (directory / MANIFEST_FILENAME).is_file():
                targets.append(directory)
            else:
                skipped.append((directory, "no .skillforge.json (not generated by SkillForge)"))
        if include_exports:
            for exporter_id in exporter_ids():
                exporter = get_exporter(exporter_id)
                for directory in list_skill_directories(exporter.skills_root(repo_root)):
                    if (directory / MANIFEST_FILENAME).is_file():
                        targets.append(directory)
                    else:
                        skipped.append(
                            (directory, f"{exporter.display_name}: no manifest, left untouched")
                        )

        for directory in targets:
            if not is_within(directory, repo_root) and not is_within(directory, Path.home()):
                raise SecurityRefusal(f"Refusing to delete outside the repository: {directory}")

        removed: list[str] = []
        if yes:
            for directory in targets:
                shutil.rmtree(directory, ignore_errors=False)
                removed.append(str(directory))

        if state.json_mode:
            emit_json(
                state,
                {
                    "would_remove": [str(directory) for directory in targets],
                    "removed": removed,
                    "skipped": [{"path": str(path), "reason": reason} for path, reason in skipped],
                    "confirmed": bool(yes),
                },
            )
            return

        console = state.console
        table = Table(title="Generated skills", title_justify="left")
        table.add_column("Path", style="dim")
        table.add_column("Action")
        for directory in targets:
            table.add_row(str(directory), "removed" if yes else "would remove")
        for path_item, reason in skipped:
            table.add_row(str(path_item), f"kept: {reason}")
        console.print(table)
        if not targets:
            console.print("[dim]Nothing to clean.[/dim]")
        elif not yes:
            console.print("\n[bold]Dry run[/bold]: re-run with [bold]--yes[/bold] to delete.")


__all__ = ["register"]
