#!/usr/bin/env python3
# Generated by SkillForge from repository evidence. Review before running.
"""Compare the running API with its OpenAPI document (read-only).

Fetches ``/openapi.json`` from a running instance and lists the routes. Use it
to confirm which endpoints exist before changing a contract. It performs GET
requests only, sends no credentials, and never mutates server state.
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.error
import urllib.request

DEFAULT_BASE_URL = __SKILLFORGE_DEFAULT_BASE_URL__
SPEC_PATHS = __SKILLFORGE_SPEC_PATHS__


def fetch(url: str, timeout: float) -> dict:
    request = urllib.request.Request(url, headers={"Accept": "application/json"})
    with urllib.request.urlopen(request, timeout=timeout) as response:
        payload = response.read().decode("utf-8", errors="replace")
    data = json.loads(payload)
    if not isinstance(data, dict):
        raise ValueError("unexpected OpenAPI document shape")
    return data


def main() -> int:
    parser = argparse.ArgumentParser(description="List OpenAPI routes from a running service.")
    parser.add_argument(
        "--base-url",
        default=DEFAULT_BASE_URL,
        help="base URL of the running service",
    )
    parser.add_argument("--timeout", type=float, default=5.0, help="request timeout in seconds")
    parser.add_argument("--json", action="store_true", help="print the route table as JSON")
    parser.add_argument("--path", default="/openapi.json", help="path of the OpenAPI document")
    args = parser.parse_args()

    url = args.base_url.rstrip("/") + args.path
    try:
        document = fetch(url, args.timeout)
    except (urllib.error.URLError, ValueError, TimeoutError) as exc:
        print(f"Could not read {url}: {exc}")
        print("Start the service first (see the project-runner skill), then retry.")
        return 1

    info = document.get("info") or {}
    paths = document.get("paths") or {}
    routes = []
    for path, operations in sorted(paths.items()):
        if not isinstance(operations, dict):
            continue
        for method, operation in sorted(operations.items()):
            if method.lower() not in {"get", "post", "put", "patch", "delete", "options", "head"}:
                continue
            summary = ""
            if isinstance(operation, dict):
                summary = str(operation.get("summary") or operation.get("operationId") or "")
            routes.append({"method": method.upper(), "path": path, "summary": summary})

    if args.json:
        print(json.dumps({"info": info, "routes": routes}, indent=2))
        return 0

    title = info.get("title") or "API"
    version = info.get("version") or "unknown"
    print(f"{title} {version} — {len(routes)} route(s) from {url}")
    width = max((len(route["path"]) for route in routes), default=10)
    for route in routes:
        print(f"  {route['method']:<6} {route['path']:<{width}}  {route['summary']}")
    if not routes:
        print("  (the document contains no paths)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
