#!/usr/bin/env python3
# Generated by SkillForge from repository evidence. Review before running.
"""Collect read-only debugging context.

Prints tool versions, git state, and the presence of key files. Never prints
environment variable values (only declared names from templates).
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

# Tools worth reporting for this repository (from analysis evidence).
TOOLS = __SKILLFORGE_TOOLS__

# Files that carry configuration or entry points (relative to the repo root).
KEY_FILES = __SKILLFORGE_KEY_FILES__

# Environment variable names declared in templates (names only, never values).
ENVIRONMENT_KEYS = __SKILLFORGE_ENVIRONMENT_KEYS__

GIT_COMMANDS = [
    ("git status", ["git", "status", "--short", "--branch"]),
    ("git log", ["git", "log", "--oneline", "-n", "10"]),
    ("git diff --stat", ["git", "diff", "--stat"]),
]


def capture(argv: list[str], cwd: str) -> str:
    try:
        completed = subprocess.run(
            argv, cwd=cwd, capture_output=True, text=True, timeout=20, check=False, shell=False
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return f"<failed: {exc}>"
    output = (completed.stdout or completed.stderr or "").strip()
    return output or "<no output>"


def main() -> int:
    parser = argparse.ArgumentParser(description="Collect read-only debugging context.")
    parser.add_argument("--root", default=".", help="repository root (default: current directory)")
    parser.add_argument("--json", action="store_true", help="print JSON instead of text")
    args = parser.parse_args()
    root = Path(args.root).resolve()

    tools = {}
    for tool in TOOLS:
        if shutil.which(tool) is None:
            tools[tool] = "not found"
            continue
        tools[tool] = capture([tool, "--version"], str(root)).splitlines()[0]

    git = {label: capture(argv, str(root)) for label, argv in GIT_COMMANDS}
    files = {name: (root / name).exists() for name in KEY_FILES}

    if args.json:
        print(json.dumps({"tools": tools, "git": git, "files": files}, indent=2))
        return 0

    print("== Tool versions ==")
    for tool, version in tools.items():
        print(f"  {tool:<14} {version}")
    print("\n== Git state ==")
    for label, output in git.items():
        print(f"  $ {label}")
        for line in output.splitlines()[:12]:
            print(f"      {line}")
    print("\n== Key files ==")
    for name, exists in files.items():
        print(f"  [{'x' if exists else ' '}] {name}")
    if ENVIRONMENT_KEYS:
        print("\n== Environment variables declared in templates (names only) ==")
        for key in ENVIRONMENT_KEYS:
            print(f"  {key}")
    print("\nReminder: this script is read-only. Do not paste secrets into tickets or prompts.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
