#!/usr/bin/env python3
# Generated by SkillForge from repository evidence. Review before running.
"""Report database migration state without touching the database.

Supports two common layouts:

* Alembic: parses ``revision`` / ``down_revision`` from ``versions/*.py`` and
  reports the revision graph, heads, and orphaned revisions.
* Prisma: lists timestamped migration directories in order.

Everything here is static file inspection. Use the project's own read-only
command (for example ``alembic current``) to learn which revision a database is
actually on.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ALEMBIC_DIRS = __SKILLFORGE_ALEMBIC_DIRS__
PRISMA_DIRS = __SKILLFORGE_PRISMA_DIRS__

REVISION_RE = re.compile(r"^revision(?::\s*str)?\s*=\s*[\"']([^\"']+)[\"']", re.MULTILINE)
DOWN_REVISION_RE = re.compile(
    r"^down_revision(?::[^=]+)?\s*=\s*(?:[\"']([^\"']+)[\"']|\(([^)]*)\)|None)", re.MULTILINE
)


def parse_alembic(directory: Path) -> dict:
    revisions: dict[str, str | None] = {}
    files: dict[str, str] = {}
    for path in sorted(directory.rglob("*.py")):
        text = path.read_text(encoding="utf-8", errors="replace")
        revision_match = REVISION_RE.search(text)
        if revision_match is None:
            continue
        revision = revision_match.group(1)
        down_match = DOWN_REVISION_RE.search(text)
        down: str | None = None
        if down_match is not None:
            if down_match.group(1):
                down = down_match.group(1)
            elif down_match.group(2):
                listed = [part.strip().strip("\"'") for part in down_match.group(2).split(",")]
                down = ",".join(part for part in listed if part and part != "None") or None
        revisions[revision] = down
        files[revision] = str(path.relative_to(directory.parent))

    children: dict[str, list[str]] = {revision: [] for revision in revisions}
    for revision, down in revisions.items():
        if down:
            for parent in down.split(","):
                if parent in children:
                    children[parent].append(revision)
    heads = sorted(revision for revision, kids in children.items() if not kids)
    referenced = {parent for down in revisions.values() if down for parent in down.split(",")}
    orphaned = sorted(revision for revision in revisions if revision not in referenced and revisions[revision] is not None)
    return {
        "revisions": {revision: {"down_revision": down, "file": files[revision]} for revision, down in sorted(revisions.items())},
        "heads": heads,
        "orphaned": orphaned,
    }


def parse_prisma(directory: Path) -> list[str]:
    return sorted(item.name for item in directory.iterdir() if item.is_dir())


def main() -> int:
    parser = argparse.ArgumentParser(description="Report migration state (read-only).")
    parser.add_argument("--root", default=".", help="repository root (default: current directory)")
    parser.add_argument("--json", action="store_true", help="print JSON output")
    args = parser.parse_args()
    root = Path(args.root).resolve()

    report: dict[str, object] = {"alembic": {}, "prisma": {}}
    alembic_found = False
    for relative in ALEMBIC_DIRS:
        directory = root / relative / "versions"
        if not directory.is_dir():
            directory = root / relative
        if directory.is_dir():
            alembic_found = True
            report["alembic"] = {"directory": str(directory.relative_to(root)), **parse_alembic(directory)}

    prisma_found = False
    for relative in PRISMA_DIRS:
        directory = root / relative
        if directory.is_dir():
            prisma_found = True
            report["prisma"] = {"directory": relative, "migrations": parse_prisma(directory)}

    if args.json:
        print(json.dumps(report, indent=2))
        return 0

    if not alembic_found and not prisma_found:
        print("No Alembic or Prisma migration layout was detected in this repository.")
        return 0

    if alembic_found:
        alembic = report["alembic"]
        print(f"Alembic migrations: {alembic.get('directory')}")
        revisions = alembic.get("revisions", {})
        print(f"  {len(revisions)} revision(s)")
        for revision, data in revisions.items():
            print(f"    {revision}  <- {data['down_revision'] or 'base'}  ({data['file']})")
        heads = alembic.get("heads", [])
        print(f"  heads: {', '.join(heads) if heads else 'none'}")
        if len(heads) > 1:
            print("  WARNING: multiple heads detected — a merge revision is probably required.")
        orphaned = alembic.get("orphaned", [])
        if orphaned:
            print(f"  WARNING: orphaned revisions (no parent points to them): {', '.join(orphaned)}")
    if prisma_found:
        prisma = report["prisma"]
        print(f"Prisma migrations: {prisma.get('directory')}")
        for name in prisma.get("migrations", []):
            print(f"    {name}")
    print("\nThis report is static. Confirm the live revision with the project's own command.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
