#!/usr/bin/env python3
# Generated by SkillForge from repository evidence. Review before running.
"""Read-only environment preflight for this project.

Checks that the tools and files this skill depends on are present.
It never installs anything and never runs project commands.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

# Required tools: names that must be on PATH for the documented commands to work.
REQUIRED_TOOLS = __SKILLFORGE_REQUIRED_TOOLS__

# Optional tools: useful but not required.
OPTIONAL_TOOLS = __SKILLFORGE_OPTIONAL_TOOLS__

# Files that must exist, relative to the repository root.
REQUIRED_FILES = __SKILLFORGE_REQUIRED_FILES__

VERSION_ARGS = {"uv": ["--version"], "docker": ["--version"], "python": ["--version"]}


def probe(tool: str) -> tuple[bool, str]:
    path = shutil.which(tool)
    if path is None:
        return False, "not found on PATH"
    argv = [tool, *VERSION_ARGS.get(tool, ["--version"])]
    try:
        completed = subprocess.run(
            argv, capture_output=True, text=True, timeout=10, check=False, shell=False
        )
        first = (completed.stdout or completed.stderr or "").strip().splitlines()
        return True, first[0] if first else path
    except (OSError, subprocess.SubprocessError) as exc:  # pragma: no cover - environment specific
        return True, f"found but version check failed: {exc}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Check that this skill's prerequisites are available.")
    parser.add_argument("--json", action="store_true", help="print machine-readable output")
    parser.add_argument(
        "--root", default=".", help="repository root to check (default: current directory)"
    )
    args = parser.parse_args()
    root = Path(args.root).resolve()

    results = []
    problems = 0
    for tool in REQUIRED_TOOLS:
        ok, detail = probe(tool)
        results.append({"kind": "tool", "name": tool, "required": True, "ok": ok, "detail": detail})
        if not ok:
            problems += 1
    for tool in OPTIONAL_TOOLS:
        ok, detail = probe(tool)
        results.append({"kind": "tool", "name": tool, "required": False, "ok": ok, "detail": detail})
    for relative in REQUIRED_FILES:
        exists = (root / relative).exists()
        results.append(
            {"kind": "file", "name": relative, "required": True, "ok": exists, "detail": "" if exists else "missing"}
        )
        if not exists:
            problems += 1

    if args.json:
        print(json.dumps({"ok": problems == 0, "results": results}, indent=2))
        return 1 if problems else 0

    print(f"SkillForge preflight for {root}")
    for item in results:
        marker = "OK " if item["ok"] else ("MISSING" if item["required"] else "absent ")
        label = "tool" if item["kind"] == "tool" else "file"
        suffix = f"  {item['detail']}" if item["detail"] and item["ok"] else ""
        print(f"  [{marker:>7}] {label} {item['name']}{suffix}")
    print()
    if problems:
        print(f"{problems} required prerequisite(s) missing. Fix these before running the workflow.")
        return 1
    print("All required prerequisites are present.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
