#!/usr/bin/env python3
# Generated by SkillForge from repository evidence. Review before running.
"""Pre-release checklist. Read-only: it inspects state and never publishes.

Checks: working tree cleanliness, changelog presence, declared version,
release-relevant files, and the commands the project uses for tests and builds.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

VERSION_SOURCES = __SKILLFORGE_VERSION_SOURCES__
CHANGELOG_CANDIDATES = __SKILLFORGE_CHANGELOG_CANDIDATES__
DEPLOY_COMMANDS = __SKILLFORGE_DEPLOY_COMMANDS__


def capture(argv: list[str], cwd: str) -> str:
    try:
        completed = subprocess.run(
            argv, cwd=cwd, capture_output=True, text=True, timeout=20, check=False, shell=False
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return f"<failed: {exc}>"
    return (completed.stdout or "").strip()


def read_version(root: Path, relative: str, pattern: str) -> str | None:
    path = root / relative
    if not path.is_file():
        return None
    match = re.search(pattern, path.read_text(encoding="utf-8", errors="replace"), re.MULTILINE)
    return match.group(1) if match else None


def main() -> int:
    parser = argparse.ArgumentParser(description="Read-only release checklist.")
    parser.add_argument("--root", default=".", help="repository root (default: current directory)")
    parser.add_argument("--json", action="store_true", help="print JSON output")
    args = parser.parse_args()
    root = Path(args.root).resolve()

    status = capture(["git", "status", "--porcelain"], str(root))
    branch = capture(["git", "rev-parse", "--abbrev-ref", "HEAD"], str(root))
    dirty = bool(status)

    changelog = next((name for name in CHANGELOG_CANDIDATES if (root / name).is_file()), None)
    versions = {}
    for relative, pattern in VERSION_SOURCES:
        version = read_version(root, relative, pattern)
        if version:
            versions[relative] = version

    checks = [
        {"name": "git repository", "ok": branch != "", "detail": branch or "no branch detected"},
        {"name": "working tree clean", "ok": not dirty, "detail": status or "clean"},
        {"name": "changelog present", "ok": changelog is not None, "detail": changelog or "no changelog found"},
        {"name": "version declared", "ok": bool(versions), "detail": json.dumps(versions) if versions else "no version found"},
    ]

    if args.json:
        print(json.dumps({"checks": checks, "deploy_commands": DEPLOY_COMMANDS}, indent=2))
        return 0 if all(check["ok"] for check in checks[:2]) else 1

    print(f"Release checklist for {root}")
    for check in checks:
        print(f"  [{'x' if check['ok'] else ' '}] {check['name']}: {check['detail']}")
    if DEPLOY_COMMANDS:
        print("\nDeployment commands recorded from repository evidence (require review):")
        for command in DEPLOY_COMMANDS:
            print(f"  {command}")
    print("\nReminders:")
    print("  - Tests must pass before releasing (see the test-runner skill).")
    print("  - Confirm the version bump and changelog entry with the maintainers.")
    print("  - Publishing or deploying changes state outside the repository; confirm first.")
    return 0 if all(check["ok"] for check in checks[:2]) else 1


if __name__ == "__main__":
    sys.exit(main())
