#!/usr/bin/env python3
# Generated by SkillForge from repository evidence. Review before running.
"""Run the commands discovered for this skill.

Safety model:

* Only the commands listed in ``STEPS`` can run — nothing is improvised.
* ``SAFE`` steps run by default; ``REVIEW_REQUIRED`` steps need ``--confirm``.
* Commands containing shell metacharacters are never executed; they are printed
  for manual review instead.
* Destructive commands were excluded at generation time and cannot appear here.

Run it from the repository root (or pass ``--root``); step working directories
are relative to that root.
"""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import sys
from pathlib import Path

STEPS = __SKILLFORGE_STEPS__

SHELL_METACHARACTERS = ("&&", "||", "|", ";", ">", "<", "$(", "`")


def find_step(step_id: str) -> dict | None:
    for step in STEPS:
        if step["id"] == step_id:
            return step
    return None


def describe(step: dict) -> str:
    return f"[{step['risk']:>15}] {step['id']}: {step['command']}"


def run_step(step: dict, *, root: Path, confirm: bool, timeout: int) -> int:
    command = step["command"]
    if step["risk"] != "SAFE" and not confirm:
        print(f"SKIP {step['id']}: {step['risk']} requires --confirm -> {command}")
        return 2
    if any(token in command for token in SHELL_METACHARACTERS):
        print(f"MANUAL {step['id']}: contains shell syntax, run it yourself:\n  {command}")
        return 3
    argv = shlex.split(command)
    if not argv:
        print(f"SKIP {step['id']}: empty command")
        return 2
    cwd = step.get("cwd") or "."
    working_directory = (root / cwd).resolve()
    if not working_directory.is_dir():
        print(
            f"FAIL {step['id']}: working directory does not exist: {working_directory}\n"
            "      Run this script from the repository root (or pass --root)."
        )
        return 4
    print(f"RUN  {step['id']} (cwd={cwd}): {command}")
    try:
        completed = subprocess.run(
            argv, cwd=str(working_directory), check=False, timeout=timeout, shell=False
        )
    except FileNotFoundError:
        print(f"FAIL {step['id']}: executable not found: {argv[0]}")
        return 127
    except subprocess.TimeoutExpired:
        print(f"FAIL {step['id']}: timed out after {timeout}s")
        return 124
    print(f"EXIT {step['id']}: {completed.returncode}")
    return completed.returncode


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the repository commands recorded in this skill.")
    parser.add_argument("--list", action="store_true", help="list the available steps")
    parser.add_argument("--step", action="append", default=[], help="run one step by id")
    parser.add_argument(
        "--all", action="store_true", help="run every step (safe steps only unless --confirm)"
    )
    parser.add_argument("--confirm", action="store_true", help="allow REVIEW_REQUIRED steps")
    parser.add_argument("--safe-only", action="store_true", help="only run SAFE steps, even with --all")
    parser.add_argument("--timeout", type=int, default=600, help="per-step timeout in seconds")
    parser.add_argument("--root", default=".", help="repository root (default: current directory)")
    parser.add_argument("--json", action="store_true", help="print the step list as JSON")
    args = parser.parse_args()
    root = Path(args.root).expanduser().resolve()

    if args.json:
        print(json.dumps(STEPS, indent=2))
        return 0

    if not args.step and not args.all:
        print("Available steps:")
        for step in STEPS:
            print("  " + describe(step))
        print("\nUse --step <id>, --all, or --confirm for review-level steps.")
        return 0

    selected = []
    for step_id in args.step:
        step = find_step(step_id)
        if step is None:
            print(f"Unknown step: {step_id}")
            return 2
        selected.append(step)
    if args.all:
        selected = [
            step
            for step in STEPS
            if step["risk"] == "SAFE" or (args.confirm and not args.safe_only)
        ]

    worst = 0
    for step in selected:
        code = run_step(step, root=root, confirm=args.confirm, timeout=args.timeout)
        worst = max(worst, code if code != 2 else 0)
    return worst


if __name__ == "__main__":
    sys.exit(main())

