"""Domain models for SkillForge (pure data, no I/O)."""

from __future__ import annotations

from skillforge.models.common import (
    Certainty,
    Evidence,
    RiskLevel,
    Severity,
    Unknown,
    confidence_from_evidence,
)
from skillforge.models.doctor import CheckStatus, DoctorReport, ToolCheck
from skillforge.models.evaluation import (
    NOT_MEASURED,
    CheckOutcome,
    ComparisonRow,
    EvaluationReport,
    MetricValue,
    ScenarioResult,
)
from skillforge.models.repository import (
    API,
    SCHEMA_VERSION,
    Command,
    ComponentKind,
    Database,
    Dependency,
    DependencyScope,
    DetectedTechnology,
    DocFile,
    DocKind,
    FileStats,
    GitSummary,
    LanguageStat,
    ProjectComponent,
    RepositoryProfile,
    Risk,
    Service,
    TechnologyKind,
    Workflow,
)
from skillforge.models.skill import (
    COMPATIBILITY_MAX,
    DESCRIPTION_MAX,
    MANIFEST_FILENAME,
    SKILL_MD_MAX_LINES,
    SKILL_MD_TOKEN_WARN,
    SKILL_NAME_MAX,
    SUPPORTED_RESOURCE_DIRS,
    GeneratedSkill,
    GenerationMode,
    ProvenanceEntry,
    ProvenanceOrigin,
    SkillBundle,
    SkillCandidate,
    SkillFile,
    SkillManifest,
    SkillMetadata,
    SkillPlan,
    is_valid_skill_name,
)
from skillforge.models.validation import (
    FindingSeverity,
    ValidationFinding,
    ValidationResult,
)

__all__ = [
    "API",
    "COMPATIBILITY_MAX",
    "DESCRIPTION_MAX",
    "MANIFEST_FILENAME",
    "NOT_MEASURED",
    "SCHEMA_VERSION",
    "SKILL_MD_MAX_LINES",
    "SKILL_MD_TOKEN_WARN",
    "SKILL_NAME_MAX",
    "SUPPORTED_RESOURCE_DIRS",
    "Certainty",
    "CheckOutcome",
    "CheckStatus",
    "Command",
    "ComparisonRow",
    "ComponentKind",
    "Database",
    "Dependency",
    "DependencyScope",
    "DetectedTechnology",
    "DocFile",
    "DocKind",
    "DoctorReport",
    "EvaluationReport",
    "Evidence",
    "FileStats",
    "FindingSeverity",
    "GeneratedSkill",
    "GenerationMode",
    "GitSummary",
    "LanguageStat",
    "MetricValue",
    "ProjectComponent",
    "ProvenanceEntry",
    "ProvenanceOrigin",
    "RepositoryProfile",
    "Risk",
    "RiskLevel",
    "ScenarioResult",
    "Service",
    "Severity",
    "SkillBundle",
    "SkillCandidate",
    "SkillFile",
    "SkillManifest",
    "SkillMetadata",
    "SkillPlan",
    "TechnologyKind",
    "ToolCheck",
    "Unknown",
    "ValidationFinding",
    "ValidationResult",
    "Workflow",
    "confidence_from_evidence",
    "is_valid_skill_name",
]
